# syntax=docker/dockerfile:1

FROM docker.io/gentoo/portage:latest@sha256:c5b4aa221cc3a65e331407022d5e515363ae0166bb0918e02809cc8e22441dd9 AS portage

FROM docker.io/gentoo/stage3:latest@sha256:08914e15d306bfdb251262ca3f7e3489b77ca32604ad1928cbb21dc94587261c

LABEL org.opencontainers.image.source="https://github.com/jkxyz/ebuilds"

COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo
COPY .github/gentoo-tools/gentoo.conf /etc/portage/repos.conf

RUN USE="text" emerge --getbinpkg --jobs=2 --oneshot \
        app-portage/gentoolkit \
        app-portage/mgorny-dev-scripts \
        dev-util/pkgcheck \
        dev-util/pkgdev \
        dev-vcs/git \
    && rm -rf /var/cache/distfiles/* /var/cache/binpkgs/*

WORKDIR /var/db/repos/jkxyz-ebuilds
