# Space-separated users for whom the OpenRC service should run Dropbox.
DROPBOX_USERS=""

# Integer from -20 (highest priority) to 19 (lowest priority).
#NICE=0

# See start-stop-daemon(8) for supported I/O scheduling classes.
#IONICE=2
